### ISSUE TITLE
scripts/mypca.R

### ISSUE THREAD

**Issue by mocherry** [ScienceParkStudyGroup/rna-seq-lesson#13]
Dear ScienceParkStudyGroup-Team,

I am struggling with your Introduction to RNA-seq lessons.
I managed to start a RStudio instance in the browser and now tried to follow Episode 05. However I got stuck at the very beginning when I try to execute:
source("scripts/mypca.R")
This is followed by an error:
**Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'scripts/mypca.R': No such file or directory**

My this is a trivial problem, but I cannot figure out where it comes from.

Help would be appreciated
Thanks and best,
Matthias

---

**Comment by mgalland** [comment]
Hello @mocherry that's an easy fix for you hopefully. 

Normally, the Docker rnaseq-2021 image that is referenced in the [Setup section of the lesson](https://scienceparkstudygroup.github.io/rna-seq-lesson/setup.html#13-the-rnaseq-2021-image-for-count-data-analysis-episodes-05-06-and-07) should contain the `scripts/mypca.R` file. I checked and it does not. My bad. 

For now, you can either use the Docker rnaseq-latest image with `docker pull scienceparkstudygroup/master-gls:rnaseq-latest`. I will fix and make a stable image later this month.  

In the meantime, if you prefer not to use Docker, [here is the link to the `mypca.R` script](https://github.com/ScienceParkStudyGroup/docker-images-for-teaching/blob/master/rnaseq/scripts/mypca.R). 
Save it and source it to load the mypca function. 

All the best
Marc

**Comment by mgalland** [comment]
The code is now visible and available at https://scienceparkstudygroup.github.io/rna-seq-lesson/extra_functions/index.html#1-custom-pca-function 

This will help in case someone wants to follow the lesson locally without the rnaseq Docker image and its embedded `mypca.R` script.
